name: Release

on:
  push:
    branches: [main, release-candidate, develop]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write
  packages: read

jobs:
  release:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/typescript-release.yml@v1.28.5
    with:
      node_version: "22"
    secrets: inherit
